USE [master]
GO

IF EXISTS (select * from sys.databases where [name] = 'Tweets')
   DROP DATABASE [Tweets]
GO

/****** Object:  Database [Tweets]    Script Date: 18/05/2014 1:58:14 AM ******/
CREATE DATABASE [Tweets]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tweets', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Tweets.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Tweets_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Tweets_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Tweets] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tweets].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tweets] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tweets] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Tweets] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Tweets] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Tweets] SET ARITHABORT OFF 
GO

ALTER DATABASE [Tweets] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Tweets] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Tweets] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tweets] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tweets] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tweets] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tweets] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Tweets] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tweets] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Tweets] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tweets] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Tweets] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tweets] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tweets] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tweets] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tweets] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tweets] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tweets] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tweets] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Tweets] SET  MULTI_USER 
GO

ALTER DATABASE [Tweets] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tweets] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Tweets] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Tweets] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Tweets] SET  READ_WRITE 
GO

CREATE TABLE Tweets.dbo.Category
	(
	Id int NOT NULL,
	Name nvarchar(MAX) NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE Tweets.dbo.Category ADD CONSTRAINT
	PK_Category PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE Tweets.dbo.Category SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE Tweets.dbo.Tweet
	(
	Id int NOT NULL,
	Tweet_Id nvarchar(50) NULL,
	Author nvarchar(50) NULL,
	Entity_Id nvarchar(50) NULL,
	Category nvarchar(MAX) NULL,
	Text nvarchar(MAX) NULL,
	Id_Category int NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE Tweets.dbo.Tweet ADD CONSTRAINT
	PK_Tweet PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE Tweets.dbo.Tweet
ADD CONSTRAINT FK_Tweet_Category FOREIGN KEY (Id_Category) 
    REFERENCES Category (Id) 
    ON DELETE CASCADE
    ON UPDATE CASCADE
;

ALTER TABLE Tweets.dbo.Tweet SET (LOCK_ESCALATION = TABLE)
GO

